### ISSUE TITLE
Batch support for prepared statements

### ISSUE THREAD

**Issue by idlebear** [datastax/nodejs-driver#36]
Is there any plan to support prepared statements with batch requests?   The driver currently ignores the {prepare:true} option.  

Alternatively, how can I hint at a data type when using a batch statement.  I have the following table definition:

    CREATE TABLE foo.bar {
        ...
        strings   map<text, text>,
        ...
    };

Calling a batch insert with the strings parameter:    { one: 'string 1', two: 'string 2' }

Fails with:
    [TypeError: Target data type could not be guessed, you should use prepared statements for accurate type mapping. Value: { one: 'string 1',  two: 'string 2' }]

Thanks.

**Comment by jorgebay** [comment]
Batch of prepared statements are supported in v2.0 of the driver, you should update and it should work, see the last part of [this blog post for more info](http://www.datastax.com/dev/blog/nodejs-cassandra-javascript-type-support).

**Comment by idlebear** [comment]
Thanks!  Solved by upgrading to the new driver.
