### ISSUE TITLE
query: 'DESCRIBE TABLE <keyspaceName>.<tableName>;'  fails.

### ISSUE THREAD

**Issue by UnbounDev** [datastax/nodejs-driver#37]
Using the client to execute query `'DESCRIBE TABLE <keyspaceName>.<tableName>;'` (where `<keyspaceName>` and `<tableName>` represent an existing keyspace/table pair) fails w/ the following error:

```
{ [ResponseError: line 1:0 no viable alternative at input 'DESCRIBE']
  name: 'ResponseError',
  message: 'line 1:0 no viable alternative at input \'DESCRIBE\'',
  info: 'Represents an error message from the server',
  code: 8192,
  query: 'DESCRIBE TABLE <keyspaceName>.<tableName>;' }
```

Note that the query runs successfully when executed via the CQL shell.

**Comment by jorgebay** [comment]
`DESCRIBE` is a `cqlsh`command but not a valid cql syntax, at least [for now](https://issues.apache.org/jira/browse/CASSANDRA-8005) :)

**Comment by kedashoe** [comment]
cqlsh supports command line query arguments, so a workaround in the meantime could be something like

    var exec = require('child_process').exec;
    exec('cqlsh -e "desc table <keyspaceName>.<tableName>"', function(err, response){ ... });

**Comment by jorgebay** [comment]
I would recommend [querying the system tables](https://www.datastax.com/documentation/cql/3.1/cql/cql_using/use_query_system_c.html) instead.

**Comment by kedashoe** [comment]
> I would recommend querying the system tables instead.

Good call :) Was going to mention performance. For what I was doing speed did not matter at all and I just wanted a simple way to backup the table schema.

**Comment by UnbounDev** [comment]
Thanks for the quick response - and the tip! I'll work around q/ the system tables while waiting for `DESCRIBE` to make it into cql.
