### ISSUE TITLE
implement mongoose.connect like connection sharing in nodejs-drive

### ISSUE THREAD

**Issue by programming-kid** [datastax/nodejs-driver#38]
hi
 I have recently started using nodejs and cassandra, i am switching from mongodb  currently using ```mongooseJS``` as node-mongo client .

This is one of the best writter client library i have ever used, it has all the necessary features for a database client library,  load balancing, node discovery , retry policy etc.

There this one thing i miss from ```mongooseJS``` is, in ```mongooseJS``` mongoose.connect() caches the connection string and u can simply use 
```javascript
var mongoose = require("mnongoose");
```
in any file  you require it , by just calling mongoose.connect() once during application startup.

I wish cassandra nodejs-driver would have same feature so that we don't have to require client connection in every file where we need to connect to cassandra 

if what i explained was not clear here is a [stackoverflow question](http://stackoverflow.com/questions/28966901/mongoose-connection-automatically-shared-in-express-js-application)  which explains it in detail 

i wish this gets added soon if possible 
thanks

**Comment by avalanche123** [comment]
hi @programming-kid,

Could you please file an issue on the [NodeJS driver Jira](https://datastax-oss.atlassian.net/browse/NODEJS).

Github issues are only enabled while we gather responses from previous contributors for the contribution license agreement and are not used for issue tracking.

Cheers!
