### ISSUE TITLE
Cannot include non-counter statement in a counter batch

### ISSUE THREAD

**Issue by hastiecraig** [datastax/nodejs-driver#39]
Hi,

I'm trying to perform a batch statement that includes counter and non-counter inserts/updates - however I get the above error (code 8704) when I attempt this. 

Is this supported in this driver?

Thanks.

**Comment by jorgebay** [comment]
Hi,
Its a Cassandra limitation and there is a powerful reason behind it:

*Unlike other writes, counter updates are not idempotent, so replaying them
automatically from the batchlog is not safe. Counter batches are thus
strictly for improved performance when updating multiple counters in the
same partition.*

Read more: Atomic batches in Cassandra
<http://www.datastax.com/dev/blog/atomic-batches-in-cassandra-1-2>.

So you should not include counter columns in logged batches.
To update (increment / decrement) counter columns tables in batch, you can
use the flag counter in the query options, but only include counter
mutations in the queries.

client.batch(queries, { counter: true}, callback);

Jorge

**Comment by hastiecraig** [comment]
Thanks for the speedy reply Jorge!
